In [1]:
import numpy as np 
import pandas as pd
import warnings 
warnings.filterwarnings("ignore")

In [4]:
l=[1,2,3,4]
print(l*5)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [6]:
type(l)

list

In [9]:
l1=[1,2.0,True,None,"A"]
print(type(l1))
print(l1)

<class 'list'>
[1, 2.0, True, None, 'A']


In [10]:
a=np.array([1,2,3,4])
print(type(a))
print(a*5)

<class 'numpy.ndarray'>
[ 5 10 15 20]


In [11]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6]
(6,)
1


In [13]:
a2=np.array([[1,2],[3,4],[5,6]])
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [15]:
a3=np.array([[1,2],[1,4],[4,6]])
print(a3)
print(a3.shape)
print(a3.ndim)

[[1 2]
 [1 4]
 [4 6]]
(3, 2)
2


In [17]:
z=np.zeros((3,4))
print(z)
print(z.shape)
print(z.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
2


In [18]:
z=np.zeros((3,3,3))
print(z)
print(z.shape)
print(z.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(3, 3, 3)
3


In [19]:
a5=np.random.random((3,4))
print(a5)
print(a5.shape)
print(a5.ndim)

[[0.29859775 0.46229346 0.31718261 0.89396813]
 [0.77000805 0.88465047 0.67856341 0.93186294]
 [0.25418917 0.19976159 0.39407744 0.23163757]]
(3, 4)
2


In [20]:
#np.linspace is used for equal distribution of a  specific range .

In [21]:
a6=np.linspace(0,200,10)
print(a6)
print(a6.shape)
print(a6.ndim)

[  0.          22.22222222  44.44444444  66.66666667  88.88888889
 111.11111111 133.33333333 155.55555556 177.77777778 200.        ]
(10,)
1


In [22]:
#here 0 is the starting range , 200 is the ending range and  10 is the no. of values .

In [23]:
a7=np.array([[1,2],[1,4],[4,6]])
print(a7)
print(a7.shape)
print(a7.ndim)

[[1 2]
 [1 4]
 [4 6]]
(3, 2)
2


In [24]:
a8=a7.reshape(2,3)
print(a8)
print(a8.shape)
print(a8.ndim)

[[1 2 1]
 [4 4 6]]
(2, 3)
2


In [25]:
a9=a8.reshape(6,1)
print(a9)
print(a9.shape)
print(a9.ndim)

[[1]
 [2]
 [1]
 [4]
 [4]
 [6]]
(6, 1)
2


In [27]:
a10=a9.T
print(a10)
print(a10.shape)
print(a10.ndim)

[[1 2 1 4 4 6]]
(1, 6)
2


In [30]:
a11=a8.T
a11

array([[1, 4],
       [2, 4],
       [1, 6]])

In [32]:
a=np.array([1,2,3,4,5,6]).reshape(2,3)
b=np.array([7,8,9,10,11,12]).reshape(2,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [33]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [35]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [38]:
a12=np.array([1,2,3,4,5],dtype=float)
print(a12)

[1. 2. 3. 4. 5.]


In [39]:
b2=np.array([1.,2.,3.],dtype=bool)
print(b2)

[ True  True  True]


In [41]:
b3=np.array([1,2,3,4,5])
b3

array([1, 2, 3, 4, 5])

In [42]:
b4=np.append(b3,[9,10,11])
b4

array([ 1,  2,  3,  4,  5,  9, 10, 11])

In [46]:
b5=np.insert(b4,5,[6,7,8])
b5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
#In the above syntax 5 is the index no in b4

In [49]:
b6=np.delete(b5,[2,3,4,5])
b6

array([ 1,  2,  7,  8,  9, 10, 11])

In [50]:
#In the above syntax 2,3,4,5 is the index no in b5