In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable


In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
print(a)
print(type(a))


[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
b=np.arange(1,6)
b

array([1, 2, 3, 4, 5])

In [13]:
b=np.arange(1,8,2)
b

array([1, 3, 5, 7])

In [14]:
b.reshape(2,2)

array([[1, 3],
       [5, 7]])

In [15]:
b=np.arange(2,24,4)
b

array([ 2,  6, 10, 14, 18, 22])

In [16]:
b.reshape(3,2)

array([[ 2,  6],
       [10, 14],
       [18, 22]])

In [17]:
b.reshape(2,3)

array([[ 2,  6, 10],
       [14, 18, 22]])

In [19]:
a=b.reshape(3,2)
a

array([[ 2,  6],
       [10, 14],
       [18, 22]])

In [22]:
print(a*5)

[[ 10  30]
 [ 50  70]
 [ 90 110]]


In [21]:
print(a/2)

[[ 1.  3.]
 [ 5.  7.]
 [ 9. 11.]]


In [23]:
a[2]

array([18, 22])

In [25]:
a[2,1]

22

In [26]:
a[2:3]

array([[18, 22]])

In [32]:
b=np.arange(2,24,4)
b

array([ 2,  6, 10, 14, 18, 22])

In [28]:
b[2:5]

array([10, 14, 18])

In [35]:
c=b(1,4)
c

TypeError: 'numpy.ndarray' object is not callable

In [36]:
b[-2]

18

In [40]:
a=np.arange(11,20).reshape(3,3)
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
b=a.flatten()
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
a[1:2,1:2]

array([[15]])

In [44]:
a[0:2,0:2]

array([[11, 12],
       [14, 15]])

In [45]:
a[0:2,:]

array([[11, 12, 13],
       [14, 15, 16]])

In [47]:
a[:,0:2]

array([[11, 12],
       [14, 15],
       [17, 18]])

In [48]:
a[a>15]

array([16, 17, 18, 19])

In [51]:
topic=np.array(["Marathi","Hindi","English","Maths","Marathi"])
topic

array(['Marathi', 'Hindi', 'English', 'Maths', 'Marathi'], dtype='<U7')

In [52]:
topic[topic=="Marathi"]


array(['Marathi', 'Marathi'], dtype='<U7')

In [53]:
topic[topic!="Marathi"]

array(['Hindi', 'English', 'Maths'], dtype='<U7')

In [57]:
topic[topic!="Marathi"]="History"
topic

array(['Marathi', 'History', 'History', 'History', 'Marathi'], dtype='<U7')

In [58]:
topic=np.array(["Marathi","Hindi","English","Maths","Marathi"])
topic

array(['Marathi', 'Hindi', 'English', 'Maths', 'Marathi'], dtype='<U7')

In [61]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])